title:              Lang Lab
email:              jessica.lang@wisc.edu
description:        Jessica Lang Lab website at University of Wisconsin-Madison, Translational Ovarian Cancer Genetics and Epigenetics
author:             Jessica Lang
baseurl:            "/jessicadlang.github.io"
url:                "https://jessicadlang.github.io"

# Social Profiles
twitter_username:   jessicalangphd
github_username:    jessicadlang
facebook_username: 
instagram_username: 
linkedin_username:  jessica-lang-33149a75

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
